spring:
  application:
    name: uni_ai
  profiles:
    active: dev,private
  ai:
    spark:
      chat:
        api-key: xxx
        api-secret: xxx
        appid: xxx
        enabled: true
    dash-scope:
      api-key: xxx
      enabled: true
    qian-fan:
      access-key: xxx
      secret-key: xxx
      enabled: true
    openai:
      api-key: xxx
      base-url: xxx
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8877
  tomcat:
    max-http-form-post-size: 20MB
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 自动续签
  auto-renew: true

wx:
  # 微信小程序配置，
  miniapp:
    appid: xxxx
    secret: xxxx
    config-storage:
      http-client-type: HttpClient
      type: redistemplate
  pay:
    app-id: xxxx
    mch-id: xxxx
    apiv3-key: xxxx
    cert-serial-no: xxxx
    privateKeyPath: classpath:wechat/apiclient_key.pem
    privateCertPath: classpath:wechat/apiclient_cert.pem
sms:
  provider: none
oss:
  provider: ali_yun
  ali-yun:
    access-key-id: xxx
    access-key-secret: xxx
    endpoint: xxx
    bucket-name: xxx